### PR TITLE
Abstract connection interface

### PR DESCRIPTION
**Pull request by Yuras**
As discussed in #12, I creates an abstract interface for connection, that can be used to implement ssl support. Please review.

Still to do:

 - Deduplicate code. Implement `Handle` API in terms of `Connection`
 - Add tests for `readExactly`

I'll do that if you are OK with the design.

### CODE REVIEW

**Comment by gregwebs** [comment]
looks great!

**Comment by Yuras** [comment]
@gregwebs I finished the implementation and added tests. Please review.

**Comment by Yuras** [comment]
That requires rebase, but master doesn't compile for me anymore because of around vs around_. Please ping me if you need action from me.

**Comment by gregwebs** [comment]
closing in favor of #14

**Pull request closed without merging**
