### PR TITLE
Performance optimization

### PR DESCRIPTION
**Pull request by VictorDenisov**

### CODE REVIEW

**Comment by VictorDenisov** [comment]
@gregwebs could you please take a look at this as well. Here we get rid of two layers of abstractions of dubious profit. It gives us nearly 10% performance gain for inserts. Also it makes the code much more understandable. The changes are pretty straight forward except this place https://github.com/mongodb-haskell/mongodb/pull/42/files#diff-8202d210b63e816a9e7e2bd6951dfbf7L121
here readExactly is replaced with hGet. To me they seem to be doing the same thing the same way.
So, I suggest to use hGet as a more standard variant of readExactly. Simpler code will allow us to do more performance improvements going forward.

**Comment by gregwebs** [comment]
It all looks good to me.

**Comment by Yuras** [comment]
@VictorDenisov you seem to revert #13. How can I establish secure connection to mongodb after your refactoring?

**Comment by VictorDenisov** [comment]
Hm, didn't know that I revert something. Well, then I presume we definitely need to get rid of Steam interface as redundant. Abstract connection should be enough. As far as I understand right now this code exists for future possible implementations of ssl support. Is there any work being done in this direction?

**Comment by Yuras** [comment]
I'm using ssl support in production. With the existing API ssl support is like 30 lines of code. I didn't bother releasing it. IIRC we decided not to integrate it into mongodb itself because we don't want to depend on a particular ssl implementation, hopenssl or tls.

**Comment by VictorDenisov** [comment]
Can you share your 30 lines of code? I can look into how to reconcile your ssl and my patch. Because if they are not in this code then it definitely is not worth keeping two layers of unnecessary abstraction.
Also was this "unread" function really necessary? readExactly function which uses this unread causes that 10% slowness. hGet works much faster.

**Comment by Yuras** [comment]
Sure, here is the code: http://lpaste.net/3590266074437779456

Re `unread`, we can add `readExactly` to the `Connection` interface and implement it via `hGet` for `Handle`. And probably frop `unread` if it is not used anymore.

**Comment by VictorDenisov** [comment]
@Yuras Could you please clarify if this ssl transport is for recently implemented in mongodb ssl support or for your own ssl proxy in front of mongodb server?

**Comment by Yuras** [comment]
I think it is for built-in ssl support, not for ssl proxy, but I'm not sure. I used the following instructions to enable ssl: https://docs.mongodb.org/v2.4/tutorial/configure-ssl/

**Comment by VictorDenisov** [comment]
@Yuras What's the point of using region in your code? Maximum what you want is to close the handler if context creation fails. bracketOnException should do the work just fine.

**Comment by Yuras** [comment]
@VictorDenisov I think region makes code easier, but it is just a personal preference/style. The code is part of an internal project (where `io-regions` is widely used, so an additional dependency it not an issue), and it was not intended for public release. I agree that it should be removed before public release to minimize dependencies.

**Pull request closed without merging**
