### PR TITLE
Fix slow requests to the database server

### PR DESCRIPTION
**Pull request by VictorDenisov**
This pull request addresses issue #6.

### CODE REVIEW

**Comment by gregwebs** [comment]
wow! great job figuring this out.

**Comment by VictorDenisov** [comment]
Could you please review, @gregwebs

**Comment by gregwebs** [comment]
would it make more sense to fix the definition of `writeLazy`? The way the new code builds up a list desn't seem optimal: better should be to keep putting everything or to append to a bytestring builder.

**Comment by VictorDenisov** [comment]
Ok. Let me see if I can improve it.

**Comment by VictorDenisov** [comment]
I looked into builders and it turned out that builders are just chains of functions, so, the way they are stored in memory doesn't seem to me very different from the list that I'm using now.

Just rewriting writeLazy doesn't help as well. For some reason(unfortunately I don't understand why exactly) if we output strings for notices are requests one by one then they are sent as separate packets and there is a delay of 0.01 seconds between each of them what makes the system slow. So, rewriting writeLazy only doesn't help either.

Normally this delay should be not more than 0.0001. With the implementation I suggested this delay is approximately 0.0002 and every request is sent as one tcp packet. This implementation is already slightly faster than python client.

I agree it would make sense to further improve this code, but it looks like a much bigger endeavour at the moment.

**Comment by gregwebs** [comment]
ok. can you delete `writeLazy` now?

**Comment by VictorDenisov** [comment]
Done.

**Comment by gregwebs** [comment]
Just tried this out on a large dataset I have that used to take around half a day. Done in 5 minutes :) publish this!

**Pull request merged**
