### PR TITLE
Update command

### PR DESCRIPTION
**Pull request by VictorDenisov**
This pull request addresses issue #54. It introduces bulk updates and reimplements single update in terms of bulk updates.

### CODE REVIEW

**Comment by VictorDenisov** [comment]
@gregwebs Could you please review.

**Comment by VictorDenisov** [comment]
@gregwebs Sorry. Disregard for the time being. I just realized that the new API requires usage of Internal.Protocol(UpdateOption). I need to decide what to do with it before we move on.

**Comment by VictorDenisov** [comment]
@gregwebs I fixed it by exporting UpdateOption from Query module and hiding Internal module.
I presume nobody used Internal module anyway, so, it should be ok to hide it.

**Comment by gregwebs** [comment]
Looks great!

**Pull request merged**
