### PR TITLE
Retrieve another batch for next in case of unlimited request

### PR DESCRIPTION
**Pull request by VictorDenisov**
One more fix for issue #24

### CODE REVIEW

**Comment by VictorDenisov** [comment]
@gregwebs Could you please review.

**Comment by gregwebs** [comment]
Looks fine. Would be nice to have a regression test.

**Comment by VictorDenisov** [comment]
Sure, will do.

**Comment by VictorDenisov** [comment]
@gregwebs Is it go now?

**Comment by gregwebs** [comment]
Great!

**Comment by VictorDenisov** [comment]
I'll publish this on hackage if you don't mind. It's a rather critical fix.

**Comment by jb55** [comment]
thanks!

**Pull request merged**
