### PR TITLE
Cleaning, updating codebase to avoid warnings/infos.

### PR DESCRIPTION
**Pull request by why-not-try-calmer**
Preparing the ground for future PR updating opcodes to use the OP_MSG protocol:
- replaced deprecated Consumer/Produce with ConduitT
- adjusted variables names to avoid shadowing
- removed a few unnecessary parentheses too
- simplified a handful of function bodies with fromMaybe, catMaybe, mapMaybe...
- removed unused imports.

This eliminated ~50 warnings and twice as many info messages.

Also:
- edited .gitignore to keep only "dist-newstyle/config"

### CODE REVIEW

**Comment by why-not-try-calmer** [comment]
Any news on this?

**Comment by VictorDenisov** [comment]
Will take a look this week.

On June 28, 2022 10:37:10 AM UTC, Adrien ***@***.***> wrote:
>Any news on this?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/mongodb-haskell/mongodb/pull/130#issuecomment-1168550259
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by VictorDenisov** [comment]
Is it supposed to compile? I seem to have issues building Query.hs file.

**Comment by VictorDenisov** [comment]
All looks good. I presume you don't mind if I merge it to master, do you?

**Comment by why-not-try-calmer** [comment]
> All looks good. I presume you don't mind if I merge it to master, do you?

I don't mind! I'll go back to implementing transaction then 😉

**Pull request merged**
